version: "3.3"

services:
  maria_db:
    container_name: gentil
    image: mariadb:latest # version de l'image mysql
    volumes:
      - ./data_db:/var/lib/mariadb # où seront stockée les données en local
    environment:
        MYSQL_ROOT_PASSWORD: admin_digital2022 # mot de passe root
        MYSQL_DATABASE: combatgentil_db # le nom de la db  
        MYSQL_USER: CF # votre nom d'utilisateur
        MYSQL_PASSWORD: digital2022 # votre mot de passe

  phpmyadmin:
    container_name: heros
    image: phpmyadmin/phpmyadmin:4.9 # version de l'image phpMyAdmin
    links:
      - maria_db # lien avec le mysql
    environment:
      VIRTUAL_HOST: combatgentil
      PMA_HOST: maria_db
      PMA_PORT: 3306
    ports:
      - '9000:80' # le port pour accéder à phpMyAdmin -> localhost:9000
